module.exports = {
	M : {
		MEMBERS		: "MEMBERS",
		CONTACTS	: "CONTACTS"
	},

	O : {
		SEND_TO_CONTACT 	: "SEND_TO_CONTACT",
		SEND_TO_CONTACTS	: "SEND_TO_CONTACTS",
		SEND_PHOTO 			: "SEND_PHOTO",
		CREATE_GROUP 		: "CREATE_GROUP",
		FORWARD_MESSAGE 	: "FORWARD_MESSAGE",
		SEND_TEXT_MESSAGE   : "SEND_TEXT_MESSAGE",
		SEND_IMAGE_MESSAGE  : "SEND_IMAGE_MESSAGE",
		SET_REMARK_NAME 	: "SET_REMARK_NAME",
		LOGOUT 				: "LOGOUT",
		KICK_MEMBER 		: "KICK_MEMBER"
	},

	E : {
		RECEIVE_NEW_MESSAGES : "RECEIVE_NEW_MESSAGES",
		LOGIN_PAGE 			 : "LOGIN_PAGE",
		MAIN_PAGE 			 : "MAIN_PAGE",
		GROUP_CREATED 		 : "GROUP_CREATED",
		REQUEST_MEDIA_DATA 	 : "REQUEST_MEDIA_DATA",
		MEDIA_DATA 			 : "MEDIA_DATA",
		REQUEST_MEDIA_LIST   : "REQUEST_MEDIA_LIST",
		MEDIA_LIST   		 : "MEDIA_LIST",
		MEDIA_UPLOADED       : "MEDIA_UPLOADED",
		REQUEST_SAVE_IMAGE 	 : "REQUEST_SAVE_IMAGE"
	},

	V : {
		CONTACTS_UPDATED 	: "CONTACTS_UPDATED",
		MEMBERS_UPDATED  	: "MEMBERS_UPDATED",
		CATEGORY_UPDATED 	: "CATEGORY_UPDATED",
		HELPER_MSGS_UPDATED : "HELPER_MSGS_UPDATED",
		KEYWORDS_UPDATED 	: "KEYWORDS_UPDATED",
		WHITE_LIST_UPDATED 	: "WHITE_LIST_UPDATED"
	},

	DOM : {
		CHANGE : "CHANGE"
	},

	PAGE: {
		"LOADING"	: 1,
		"LOGIN" 	: 2,
		"MAIN"  	: 3,
		"SETTING"   : 4
	},

	"CREATE_GROUP_CD" : 20,
	"SEND_MESSAGE_CD" : 5,

	STORAGE: {
		"CATEGORY" 			: 1,
		"GROUP"    			: 2,
		"HELLO_MESSAGE" 	: 3,
		"LAST_CREATE_TIME"	: 4,
		"KEYWORDS"			: 5,
		"WHITE_LIST"		: 6
	},

	TASK : {
		TYPE : {
			CREATE_GROUPS : 1,
			SEND_MESSAGES : 2
		},
		EVENT : {
			UPDATED: "TASKS_UPDATED"
		}
	},

	TEST_NAME : "@95f8193e35a397ee6783035bdc137818"
};